const fs = require('fs');
let content = fs.readFileSync('src/constants.ts', 'utf-8');

function updateDesc(id, newDesc) {
  const idIndex = content.indexOf(`id: "${id}"`);
  if (idIndex === -1) return;
  const descIndex = content.indexOf(`description: "`, idIndex);
  if (descIndex === -1) return;
  const testCasesIndex = content.indexOf(`",\n    testCases:`, descIndex);
  if (testCasesIndex === -1) return;
  
  const before = content.substring(0, descIndex + `description: "`.length);
  const after = content.substring(testCasesIndex);
  
  const escapedDesc = newDesc.replace(/"/g, '\\"');
  content = before + escapedDesc + after;
}

const updates = {
  "two-sum": "<p>Given an array of integers <code>nums</code> and an integer <code>target</code>, return indices of the two numbers such that they add up to <code>target</code>.</p><p>You may assume that each input would have <strong>exactly one solution</strong>, and you may not use the same element twice.</p><p>You can return the answer in any order.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> nums = [2,7,11,15], target = 9\n<strong>Output:</strong> [0,1]\n<strong>Explanation:</strong> Because nums[0] + nums[1] == 9, we return [0, 1].</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> nums = [3,2,4], target = 6\n<strong>Output:</strong> [1,2]</pre><p><strong>Example 3:</strong></p><pre><strong>Input:</strong> nums = [3,3], target = 6\n<strong>Output:</strong> [0,1]</pre><p><strong>Constraints:</strong></p><ul><li><code>2 &lt;= nums.length &lt;= 10<sup>4</sup></code></li><li><code>-10<sup>9</sup> &lt;= nums[i] &lt;= 10<sup>9</sup></code></li><li><code>-10<sup>9</sup> &lt;= target &lt;= 10<sup>9</sup></code></li><li><strong>Only one valid answer exists.</strong></li></ul><p><strong>Follow-up:</strong> Can you come up with an algorithm that is less than <code>O(n<sup>2</sup>)</code> time complexity?</p>",
  "add-two-numbers": "<p>You are given two <strong>non-empty</strong> linked lists representing two non-negative integers. The digits are stored in <strong>reverse order</strong>, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.</p><p>You may assume the two numbers do not contain any leading zero, except the number 0 itself.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> l1 = [2,4,3], l2 = [5,6,4]\n<strong>Output:</strong> [7,0,8]\n<strong>Explanation:</strong> 342 + 465 = 807.</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> l1 = [0], l2 = [0]\n<strong>Output:</strong> [0]</pre><p><strong>Example 3:</strong></p><pre><strong>Input:</strong> l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]\n<strong>Output:</strong> [8,9,9,9,0,0,0,1]</pre><p><strong>Constraints:</strong></p><ul><li>The number of nodes in each linked list is in the range <code>[1, 100]</code>.</li><li><code>0 &lt;= Node.val &lt;= 9</code></li><li>It is guaranteed that the list represents a number that does not have leading zeros.</li></ul>",
  "longest-substring-without-repeating-characters": "<p>Given a string <code>s</code>, find the length of the <strong>longest substring</strong> without repeating characters.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> s = \"abcabcbb\"\n<strong>Output:</strong> 3\n<strong>Explanation:</strong> The answer is \"abc\", with the length of 3.</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> s = \"bbbbb\"\n<strong>Output:</strong> 1\n<strong>Explanation:</strong> The answer is \"b\", with the length of 1.</pre><p><strong>Example 3:</strong></p><pre><strong>Input:</strong> s = \"pwwkew\"\n<strong>Output:</strong> 3\n<strong>Explanation:</strong> The answer is \"wke\", with the length of 3.\nNotice that the answer must be a substring, \"pwke\" is a subsequence and not a substring.</pre><p><strong>Constraints:</strong></p><ul><li><code>0 &lt;= s.length &lt;= 5 * 10<sup>4</sup></code></li><li><code>s</code> consists of English letters, digits, symbols and spaces.</li></ul>",
  "median-of-two-sorted-arrays": "<p>Given two sorted arrays <code>nums1</code> and <code>nums2</code> of size <code>m</code> and <code>n</code> respectively, return <strong>the median</strong> of the two sorted arrays.</p><p>The overall run time complexity should be <code>O(log (m+n))</code>.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> nums1 = [1,3], nums2 = [2]\n<strong>Output:</strong> 2.00000\n<strong>Explanation:</strong> merged array = [1,2,3] and median is 2.</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> nums1 = [1,2], nums2 = [3,4]\n<strong>Output:</strong> 2.50000\n<strong>Explanation:</strong> merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.</pre><p><strong>Constraints:</strong></p><ul><li><code>nums1.length == m</code></li><li><code>nums2.length == n</code></li><li><code>0 &lt;= m &lt;= 1000</code></li><li><code>0 &lt;= n &lt;= 1000</code></li><li><code>1 &lt;= m + n &lt;= 2000</code></li><li><code>-10<sup>6</sup> &lt;= nums1[i], nums2[i] &lt;= 10<sup>6</sup></code></li></ul>",
  "longest-palindromic-substring": "<p>Given a string <code>s</code>, return the longest palindromic substring in <code>s</code>.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> s = \"babad\"\n<strong>Output:</strong> \"bab\"\n<strong>Explanation:</strong> \"aba\" is also a valid answer.</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> s = \"cbbd\"\n<strong>Output:</strong> \"bb\"</pre><p><strong>Constraints:</strong></p><ul><li><code>1 &lt;= s.length &lt;= 1000</code></li><li><code>s</code> consist of only digits and English letters.</li></ul>",
  "zigzag-conversion": "<p>The string <code>\"PAYPALISHIRING\"</code> is written in a zigzag pattern on a given number of rows like this:</p><pre>P   A   H   N\nA P L S I I G\nY   I   R</pre><p>And then read line by line: <code>\"PAHNAPLSIIGYIR\"</code></p><p>Write the code that will take a string and make this conversion given a number of rows.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> s = \"PAYPALISHIRING\", numRows = 3\n<strong>Output:</strong> \"PAHNAPLSIIGYIR\"</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> s = \"PAYPALISHIRING\", numRows = 4\n<strong>Output:</strong> \"PINALSIGYAHRPI\"\n<strong>Explanation:</strong>\nP     I    N\nA   L S  I G\nY A   H R\nP     I</pre><p><strong>Constraints:</strong></p><ul><li><code>1 &lt;= s.length &lt;= 1000</code></li><li><code>s</code> consists of English letters (lower-case and upper-case), <code>','</code> and <code>'.'</code>.</li><li><code>1 &lt;= numRows &lt;= 1000</code></li></ul>",
  "reverse-integer": "<p>Given a signed 32-bit integer <code>x</code>, return <code>x</code> with its digits reversed. If reversing <code>x</code> causes the value to go outside the signed 32-bit integer range <code>[-2<sup>31</sup>, 2<sup>31</sup> - 1]</code>, then return <code>0</code>.</p><p><strong>Assume the environment does not allow you to store 64-bit integers (signed or unsigned).</strong></p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> x = 123\n<strong>Output:</strong> 321</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> x = -123\n<strong>Output:</strong> -321</pre><p><strong>Example 3:</strong></p><pre><strong>Input:</strong> x = 120\n<strong>Output:</strong> 21</pre><p><strong>Constraints:</strong></p><ul><li><code>-2<sup>31</sup> &lt;= x &lt;= 2<sup>31</sup> - 1</code></li></ul>",
  "string-to-integer-atoi": "<p>Implement the <code>myAtoi(string s)</code> function, which converts a string to a 32-bit signed integer (similar to C/C++'s <code>atoi</code> function).</p><p>The algorithm for <code>myAtoi(string s)</code> is as follows:</p><ol><li>Read in and ignore any leading whitespace.</li><li>Check if the next character (if not already at the end of the string) is <code>'-'</code> or <code>'+'</code>. Read this character in if it is either. This determines if the final result is negative or positive respectively. Assume the result is positive if neither is present.</li><li>Read in next the characters until the next non-digit character or the end of the input is reached. The rest of the string is ignored.</li><li>Convert these digits into an integer (i.e. <code>\"123\" -&gt; 123</code>, <code>\"0032\" -&gt; 32</code>). If no digits were read, then the integer is <code>0</code>. Change the sign as necessary (from step 2).</li><li>If the integer is out of the 32-bit signed integer range <code>[-2<sup>31</sup>, 2<sup>31</sup> - 1]</code>, then clamp the integer so that it remains in the range. Specifically, integers less than <code>-2<sup>31</sup></code> should be clamped to <code>-2<sup>31</sup></code>, and integers greater than <code>2<sup>31</sup> - 1</code> should be clamped to <code>2<sup>31</sup> - 1</code>.</li><li>Return the integer as the final result.</li></ol><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> s = \"42\"\n<strong>Output:</strong> 42</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> s = \"   -42\"\n<strong>Output:</strong> -42</pre><p><strong>Example 3:</strong></p><pre><strong>Input:</strong> s = \"4193 with words\"\n<strong>Output:</strong> 4193</pre><p><strong>Constraints:</strong></p><ul><li><code>0 &lt;= s.length &lt;= 200</code></li><li><code>s</code> consists of English letters (lower-case and upper-case), digits (<code>0-9</code>), <code>' '</code>, <code>'+'</code>, <code>'-'</code>, and <code>'.'</code>.</li></ul>",
  "missing-in-array": "<p>Given an array of size <code>n-1</code> such that it only contains distinct integers in the range of <code>1</code> to <code>n</code>. Find the missing element.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> n = 5, arr = [1,2,3,5]\n<strong>Output:</strong> 4\n<strong>Explanation:</strong> Given array : 1 2 3 5. Missing element is 4.</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> n = 2, arr = [1]\n<strong>Output:</strong> 2\n<strong>Explanation:</strong> Given array : 1. Missing element is 2.</pre><p><strong>Constraints:</strong></p><ul><li><code>1 &le; n &le; 10<sup>6</sup></code></li><li><code>1 &le; arr[i] &le; 10<sup>6</sup></code></li></ul><p><strong>Follow-up:</strong> Can you solve it in <code>O(n)</code> time and <code>O(1)</code> auxiliary space?</p>",
  "move-all-zeroes-to-end": "<p>Given an array <code>arr[]</code> of <code>n</code> positive integers. Push all the zeros of the given array to the right end of the array while maintaining the order of non-zero elements.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> arr = [1, 2, 0, 4, 3, 0, 5, 0]\n<strong>Output:</strong> [1, 2, 4, 3, 5, 0, 0, 0]\n<strong>Explanation:</strong> There are three 0s that are moved to the end.</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> arr = [10, 20, 30]\n<strong>Output:</strong> [10, 20, 30]\n<strong>Explanation:</strong> No zeros in array so no change.</pre><p><strong>Constraints:</strong></p><ul><li><code>1 &le; arr.length &le; 10<sup>5</sup></code></li><li><code>0 &le; arr[i] &le; 10<sup>5</sup></code></li></ul><p><strong>Follow-up:</strong> Can you solve it in <code>O(n)</code> time and <code>O(1)</code> auxiliary space?</p>",
  "reverse-words": "<p>Given a String <code>S</code>, reverse the string without reversing its individual words. Words are separated by dots.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> S = \"i.like.this.program.very.much\"\n<strong>Output:</strong> \"much.very.program.this.like.i\"\n<strong>Explanation:</strong> After reversing the whole string(not individual words), the input string becomes \"much.very.program.this.like.i\".</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> S = \"pqr.mno\"\n<strong>Output:</strong> \"mno.pqr\"\n<strong>Explanation:</strong> After reversing the whole string , the input string becomes \"mno.pqr\".</pre><p><strong>Constraints:</strong></p><ul><li><code>1 &le; |S| &le; 10<sup>5</sup></code></li></ul>",
  "roman-to-integer": "<p>Roman numerals are represented by seven different symbols: <code>I</code>, <code>V</code>, <code>X</code>, <code>L</code>, <code>C</code>, <code>D</code> and <code>M</code>.</p><pre><strong>Symbol</strong>       <strong>Value</strong>\nI             1\nV             5\nX             10\nL             50\nC             100\nD             500\nM             1000</pre><p>For example, <code>2</code> is written as <code>II</code> in Roman numeral, just two ones added together. <code>12</code> is written as <code>XII</code>, which is simply <code>X + II</code>. The number <code>27</code> is written as <code>XXVII</code>, which is <code>XX + V + II</code>.</p><p>Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not <code>IIII</code>. Instead, the number four is written as <code>IV</code>. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as <code>IX</code>. There are six instances where subtraction is used:</p><ul><li><code>I</code> can be placed before <code>V</code> (5) and <code>X</code> (10) to make 4 and 9. </li><li><code>X</code> can be placed before <code>L</code> (50) and <code>C</code> (100) to make 40 and 90. </li><li><code>C</code> can be placed before <code>D</code> (500) and <code>M</code> (1000) to make 400 and 900.</li></ul><p>Given a roman numeral, convert it to an integer.</p><p><strong>Example 1:</strong></p><pre><strong>Input:</strong> s = \"III\"\n<strong>Output:</strong> 3\n<strong>Explanation:</strong> III = 3.</pre><p><strong>Example 2:</strong></p><pre><strong>Input:</strong> s = \"LVIII\"\n<strong>Output:</strong> 58\n<strong>Explanation:</strong> L = 50, V= 5, III = 3.</pre><p><strong>Example 3:</strong></p><pre><strong>Input:</strong> s = \"MCMXCIV\"\n<strong>Output:</strong> 1994\n<strong>Explanation:</strong> M = 1000, CM = 900, XC = 90 and IV = 4.</pre><p><strong>Constraints:</strong></p><ul><li><code>1 &lt;= s.length &lt;= 15</code></li><li><code>s</code> contains only the characters <code>('I', 'V', 'X', 'L', 'C', 'D', 'M')</code>.</li><li>It is <strong>guaranteed</strong> that <code>s</code> is a valid roman numeral in the range <code>[1, 3999]</code>.</li></ul>"
};

for (const [id, desc] of Object.entries(updates)) {
  updateDesc(id, desc);
}

fs.writeFileSync('src/constants.ts', content);
console.log("Batch 1 updated");
